# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lk0N-jWWrQpwR_d698eyKFfhzkUgpT0Z
"""

import random

print("🏥 Healthcare Metrics Calculator Suite")

# -------- INPUT --------
height = input("Enter height (in meters, e.g. 1.52): ")
weight = input("Enter weight (in kg, e.g. 47.7): ")

height = float(height)
weight = float(weight)

# -------- FUNCTIONS --------
def calculate_bmi(weight, height):
    bmi = weight / (height ** 2)
    return round(bmi, 2)

def bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight ⚠️"
    elif bmi < 25:
        return "Normal ✅"
    elif bmi < 30:
        return "Overweight ⚠️"
    else:
        return "Obese 🚨"

def cardiac_output(hr, sv):
    return round((hr * sv) / 1000, 2)  # L/min

def calculate_bsa(weight, height):
    return round(0.007184 * (weight ** 0.425) * (height ** 0.725), 2)

# -------- MENU --------
print("\nChoose Calculation:")
print("1. BMI")
print("2. Cardiac Output")
print("3. Body Surface Area (BSA)")

choice = input("Enter choice (1/2/3): ")

# -------- LOGIC --------
if choice == "1":
    bmi = calculate_bmi(weight, height)
    print(f"\nYour BMI: {bmi}")
    print("Category:", bmi_category(bmi))

elif choice == "2":
    hr = float(input("Enter Heart Rate (bpm): "))
    sv = float(input("Enter Stroke Volume (ml): "))
    co = cardiac_output(hr, sv)
    print(f"\nCardiac Output: {co} L/min")

elif choice == "3":
    bsa = calculate_bsa(weight, height)
    print(f"\nBody Surface Area: {bsa} m²")

else:
    print("Invalid choice ❌")